name: Oxymoron
favicon: null
layout_spectrum: 0.20176692050881684
typography_spectrum: 0.6244606501422822
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6435931390151381
  lightness: 0.40656607202254236
  saturation: 0.1621812575031072
  rhythmicContrast: 0.4532678062096238
purpose: []
